name = "hardfloat"
# authors = ["Ethan"]
# license-file = "LICENSE"

# get berkley hardfloat
preprocessing = ["chmod +x ./get_hardfloat.sh", "./get_hardfloat.sh"]
extra_verilog = ["src/hardfloat/*.v", "src/hardfloat/*.vi"]

[compiler]
git = "git@gitlab.com:deepsilicon/spade.git"
commit = "17335fd229471458a7a7d93d8c82ae7d95213f62"
